name: build-user-manual
on: [push]
jobs:
  build-env1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor
      - run: asciidoctor source/book.adoc -b html5 -o source/book-env1.html
      - uses: actions/upload-artifact@v2
        with:
          name: output-env1
          path: |
            source/book-env1.html
            source/images

  build-env2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor
      - run: asciidoctor source/book.adoc -b html5 -o source/book-env2.html
      - uses: actions/upload-artifact@v2
        with:
          name: output-env2
          path: |
            source/book-env2.html
            source/images

  develop-release:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-18.04
    needs: [build-env1, build-env2]
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - uses: softprops/action-gh-release@v1
        with:
          body: This release is continuously updated with the latest development version. Using it is only recommended for testing.
          tag_name: latest
          prerelease: true
          token: ${{ secrets.REPOSITORY_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            output-env1/book-env1.html
            output-env2/book-env2.html