name: build-user-manual
on: [push]
jobs:
  build-user-manual-env1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor
      - run: asciidoctor source/book.adoc --backend html5
      - uses: actions/upload-artifact@v2
        with:
          name: build-output-env1
          path: |
            source/book.html
            source/images

  build-user-manual-env2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor
      - run: asciidoctor source/book.adoc --backend html5
      - uses: actions/upload-artifact@v2
        with:
          name: build-output-env2
          path: |
            source/book.html
            source/images

  develop-release:
    runs-on: ubuntu-18.04
    needs: [build-user-manual-env1, build-user-manual-env2]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-output-env1
        
      - name: Display structure of downloaded files
        run: ls -R