name: build-user-manual
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor
      - run: asciidoctor source/book.adoc --destination-dir . --backend html5
      - uses: actions/upload-artifact@v2
        with:
          name: build-output-html
          path: |
            book.html
            images