name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install asciidoctor asciidoctor-pdf
      - run: asciidoctor ./source/book.adoc --destination-dir . --backend html5
      - run: asciidoctor ./source/book.adoc --require asciidoctor-pdf --destination-dir . --backend pdf